"""合并数据库

Revision ID: 34d9b68a59ff
Revises: 58dd0344bd32
Create Date: 2026-08-03 14:58:30.855587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34d9b68a59ff'
down_revision: Union[str, Sequence[str], None] = '58dd0344bd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 不删除任何 fyz-src 的表（共用 jie_bang 数据库，各管各的表）
    op.alter_column('favorite', 'item_type',
               existing_type=mysql.VARCHAR(length=30),
               comment='收藏类型: position / learning_resource / quiz_error / knowledge_point',
               existing_comment='收藏类型',
               existing_nullable=False)
    op.alter_column('favorite', 'item_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='对应类型的资源ID',
               existing_comment='资源ID',
               existing_nullable=False)
    op.alter_column('job_position', 'salary_range',
               existing_type=mysql.VARCHAR(length=50),
               comment='薪资范围，如 15K-30K',
               existing_comment='薪资范围',
               existing_nullable=True)
    op.alter_column('learning_path', 'total_duration',
               existing_type=mysql.VARCHAR(length=50),
               comment='总学习时长，如 12周',
               existing_comment='总学习时长',
               existing_nullable=False)
    op.alter_column('match_result', 'position_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='岗位名称（冗余，方便查询）',
               existing_comment='岗位名称',
               existing_nullable=False)
    op.alter_column('match_result', 'resume_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='简历名称（冗余）',
               existing_comment='简历名称',
               existing_nullable=False)
    op.alter_column('position_skill', 'category',
               existing_type=mysql.VARCHAR(length=50),
               comment='技术栈分类，如后端/前端/AI',
               existing_comment='技术栈分类',
               existing_nullable=False)
    op.alter_column('user_resume', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='简历别名，用户自定义',
               existing_comment='简历别名',
               existing_nullable=False)
    op.alter_column('user_resume', 'work_mode',
               existing_type=mysql.VARCHAR(length=20),
               comment='工作模式: fulltime/intern/remote',
               existing_comment='工作模式',
               existing_nullable=True)
    op.alter_column('user_resume', 'source_file',
               existing_type=mysql.VARCHAR(length=200),
               comment='上传的原始文件名',
               existing_comment='原始文件名',
               existing_nullable=True)
    op.alter_column('user_resume', 'source_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='上传文件的服务器存储路径',
               existing_comment='文件存储路径',
               existing_nullable=True)
    op.alter_column('user_resume', 'raw_text',
               existing_type=mysql.TEXT(),
               comment='简历提取后的完整纯文本',
               existing_comment='提取纯文本',
               existing_nullable=True)
    op.alter_column('skill_change', 'change_date',
               existing_type=mysql.VARCHAR(length=20),
               comment='变化日期，如 2026-06',
               existing_comment='变化日期',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='邮箱')
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # user.role 由 fyz-src 管理，不在此删除
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 仅回滚 jtt-src 做的字段注释修改，不碰 fyz-src 的表
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='邮箱')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('skill_change', 'change_date',
               existing_type=mysql.VARCHAR(length=20),
               comment='变化日期',
               existing_comment='变化日期，如 2026-06',
               existing_nullable=False)
    op.alter_column('user_resume', 'raw_text',
               existing_type=mysql.TEXT(),
               comment='提取纯文本',
               existing_comment='简历提取后的完整纯文本',
               existing_nullable=True)
    op.alter_column('user_resume', 'source_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='文件存储路径',
               existing_comment='上传文件的服务器存储路径',
               existing_nullable=True)
    op.alter_column('user_resume', 'source_file',
               existing_type=mysql.VARCHAR(length=200),
               comment='原始文件名',
               existing_comment='上传的原始文件名',
               existing_nullable=True)
    op.alter_column('user_resume', 'work_mode',
               existing_type=mysql.VARCHAR(length=20),
               comment='工作模式',
               existing_comment='工作模式: fulltime/intern/remote',
               existing_nullable=True)
    op.alter_column('user_resume', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='简历别名',
               existing_comment='简历别名，用户自定义',
               existing_nullable=False)
    op.alter_column('position_skill', 'category',
               existing_type=mysql.VARCHAR(length=50),
               comment='技术栈分类',
               existing_comment='技术栈分类，如后端/前端/AI',
               existing_nullable=False)
    op.alter_column('match_result', 'resume_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='简历名称',
               existing_comment='简历名称（冗余）',
               existing_nullable=False)
    op.alter_column('match_result', 'position_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='岗位名称',
               existing_comment='岗位名称（冗余，方便查询）',
               existing_nullable=False)
    op.alter_column('learning_path', 'total_duration',
               existing_type=mysql.VARCHAR(length=50),
               comment='总学习时长',
               existing_comment='总学习时长，如 12周',
               existing_nullable=False)
    op.alter_column('job_position', 'salary_range',
               existing_type=mysql.VARCHAR(length=50),
               comment='薪资范围',
               existing_comment='薪资范围，如 15K-30K',
               existing_nullable=True)
    op.alter_column('favorite', 'item_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='资源ID',
               existing_comment='对应类型的资源ID',
               existing_nullable=False)
    op.alter_column('favorite', 'item_type',
               existing_type=mysql.VARCHAR(length=30),
               comment='收藏类型',
               existing_comment='收藏类型: position / learning_resource / quiz_error / knowledge_point',
               existing_nullable=False)
    # ### end Alembic commands ###
