"""initial

Revision ID: d181e15f9f21
Revises: 
Create Date: 2026-07-23 21:12:15.691215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd181e15f9f21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='岗位名称'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='岗位类型: new=新岗位, existing=既有岗位'),
    sa.Column('aliases', sa.JSON(), nullable=False, comment='岗位别名列表'),
    sa.Column('summary', sa.Text(), nullable=False, comment='岗位概述'),
    sa.Column('responsibilities', sa.JSON(), nullable=False, comment='核心职责列表'),
    sa.Column('industry_scenarios', sa.JSON(), nullable=False, comment='典型行业应用场景'),
    sa.Column('tech_stack', sa.JSON(), nullable=False, comment='技术栈列表'),
    sa.Column('career_level', sa.String(length=20), nullable=False, comment='职业级别: junior/mid/senior'),
    sa.Column('salary_range', sa.String(length=50), nullable=True, comment='薪资范围，如 15K-30K'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='所在城市'),
    sa.Column('education', sa.String(length=50), nullable=True, comment='最高学历'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('resume_count', sa.Integer(), nullable=False, comment='简历数量'),
    sa.Column('match_history_count', sa.Integer(), nullable=False, comment='匹配历史次数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('item_type', sa.String(length=30), nullable=False, comment='收藏类型: position / learning_resource / quiz_error / knowledge_point'),
    sa.Column('item_id', sa.String(length=100), nullable=False, comment='对应类型的资源ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='收藏项标题'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='简要描述'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='完整数据快照'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='用户自定义标签'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_item_type'), 'favorite', ['item_type'], unique=False)
    op.create_table('learning_path',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='路径名称'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='目标岗位ID'),
    sa.Column('position_name', sa.String(length=100), nullable=False, comment='目标岗位名称'),
    sa.Column('steps', sa.JSON(), nullable=False, comment='学习步骤列表'),
    sa.Column('total_duration', sa.String(length=50), nullable=False, comment='总学习时长，如 12周'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='简历别名，用户自定义'),
    sa.Column('target_position', sa.String(length=100), nullable=True, comment='目标岗位方向'),
    sa.Column('personal_name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('personal_email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('personal_phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('personal_location', sa.String(length=50), nullable=False, comment='所在地'),
    sa.Column('desired_position', sa.String(length=100), nullable=True, comment='期望职位'),
    sa.Column('desired_city', sa.String(length=50), nullable=True, comment='期望城市'),
    sa.Column('salary_expectation', sa.String(length=50), nullable=True, comment='期望薪资'),
    sa.Column('work_mode', sa.String(length=20), nullable=True, comment='工作模式: fulltime/intern/remote'),
    sa.Column('self_evaluation', sa.Text(), nullable=False, comment='自我评价'),
    sa.Column('source_file', sa.String(length=200), nullable=True, comment='上传的原始文件名'),
    sa.Column('source_file_path', sa.String(length=500), nullable=True, comment='上传文件的服务器存储路径'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='简历提取后的完整纯文本'),
    sa.Column('education_list', sa.JSON(), nullable=False, comment='教育经历列表'),
    sa.Column('work_experience_list', sa.JSON(), nullable=False, comment='工作经历列表'),
    sa.Column('project_list', sa.JSON(), nullable=False, comment='项目经历列表'),
    sa.Column('skill_list', sa.JSON(), nullable=False, comment='技能列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='技能名称'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='重要性: required/preferred/advanced'),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='类型: required=必备, preferred=加分'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='技术栈分类，如后端/前端/AI'),
    sa.ForeignKeyConstraint(['position_id'], ['job_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False, comment='变化的技能名'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='变化类型: added/removed/modified'),
    sa.Column('description', sa.Text(), nullable=False, comment='变化说明'),
    sa.Column('source', sa.String(length=200), nullable=False, comment='数据来源'),
    sa.Column('change_date', sa.String(length=20), nullable=False, comment='变化日期，如 2026-06'),
    sa.ForeignKeyConstraint(['position_id'], ['job_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='简历ID'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='岗位ID'),
    sa.Column('position_name', sa.String(length=100), nullable=False, comment='岗位名称（冗余，方便查询）'),
    sa.Column('resume_name', sa.String(length=100), nullable=False, comment='简历名称（冗余）'),
    sa.Column('total_score', sa.Integer(), nullable=False, comment='综合匹配分数 0-100'),
    sa.Column('dimensions', sa.JSON(), nullable=False, comment='各维度评分列表'),
    sa.Column('gap_analysis', sa.JSON(), nullable=False, comment='差距分析结果'),
    sa.Column('suggestions', sa.JSON(), nullable=False, comment='优化建议列表'),
    sa.Column('match_date', sa.DateTime(), nullable=False, comment='匹配时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result')
    op.drop_table('skill_change')
    op.drop_table('position_skill')
    op.drop_table('resume')
    op.drop_table('learning_path')
    op.drop_index(op.f('ix_favorite_item_type'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('job_position')
    # ### end Alembic commands ###
