[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
<<<<<<< HEAD
addopts = --cov=app --cov-config=.coveragerc --cov-report=term-missing --cov-fail-under=60
=======
addopts = --cov=app --cov-fail-under=60
>>>>>>> b568d5178201726754523d39b83e833d55cbaa23
